---
- include: manage_ssh_keys.yml
  when: deploy_ssh_key
  tags: deployment
- include: add_cloud_conf_files.yml
  tags: cloud_upload
- include: setup.yml
- include: create_libvirt_pool.yml
- include: deploy_pr_ci.yml
